### ISSUE TITLE
[#1.7] Habits to-do

### ISSUE THREAD

**Issue by geoff-B** [CMPUT301F21T30/Habiteer#7]
As a doer, I want to see what habits I need to do today.

- [x] Display all Habits to do today
- [x] Within the list, display Habit name and days that the habit repeats 
- [x] Use tabs to switch between #7 and #9
